# Generated by Django 5.1.4 on 2024-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_major_ects_university_generalenrollmentnumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="universityImage1",
            field=models.ImageField(
                blank=True, null=True, upload_to="university_images/"
            ),
        ),
    ]
