# Generated by Django 5.1.4 on 2024-12-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_university_universityimage1"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="universityImage2",
            field=models.ImageField(
                blank=True, null=True, upload_to="university_images/"
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="cityImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="university_images/"
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="cityName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
