# Generated by Django 5.1.4 on 2024-12-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_university_universityimage2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="cityImage",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="university",
            name="mapImage",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="university",
            name="universityImage1",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="university",
            name="universityImage2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
