# Generated by Django 5.1.4 on 2024-12-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_university_cityimage_alter_university_mapimage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="university",
            old_name="credit_points",
            new_name="creditPoints",
        ),
    ]
