# Generated by Django 5.1.4 on 2024-12-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_credit_points_university_creditpoints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
