# Generated by Django 5.1.4 on 2024-12-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_university_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="cityLocation",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="university",
            name="establishedIn",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="university",
            name="mapLocation",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
