# Generated by Django 5.1.4 on 2024-12-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_university_citylocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="ECTS",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="major",
            name="creditHours",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
