# Generated by Django 5.1.4 on 2024-12-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_major_ects_alter_major_credithours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="university",
            name="mapImage",
        ),
    ]
