# Generated by Django 5.1.4 on 2025-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_university_cityname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="cityImage",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="university",
            name="universityImage1",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="university",
            name="universityImage2",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
