# Generated by Django 5.1.4 on 2025-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_university_cityimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="cityName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
