name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run build.sh
        working-directory: backend
        run: bash build.sh

      - name: Export env vars
        run: |
          echo DATABASE_URL="postgres://postgres:postgres@localhost:5432/testdb" >> $GITHUB_ENV
          echo SECRET_KEY_PASSWORD="${{ secrets.SECRET_KEY_PASSWORD }}" >> $GITHUB_ENV
