name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run build.sh
        working-directory: backend
        run: bash build.sh

      - name: Run tests
        working-directory: backend
        run: python manage.py test api

      - name: Install flake8
        run: pip install flake8

      - name: Lint with flake8
        run: flake8 backend
